version: "3.2"
services:
  front:
    image: roycer/builder-front:0.1
    container_name: front
    restart: always
    ports:
      - 5432:80
    volumes:
      - ./dist:/usr/share/nginx/html/
volumes:
  html: {}